export const INITIAL_MATERIALS = [
  {
    id: 'PCB',
    nameEn: 'PCB (Circuit Board)',
    nameHi: 'सर्किट बोर्ड (PCB)',
    nameMr: 'सर्किट बोर्ड (PCB)',
    icon: '🔌',
    avgPricePerKg: 420,
    priceRange: { min: 400, max: 450 },
    subCategories: ['Green Motherboard', 'Server RAM / GPU', 'IC Chip Board', 'TV / Telecom PCB'],
    description: 'Printed Circuit Boards from Green Motherboards, RAM, GPUs, and IC boards.',
    safetyHazard: 'Contains solder lead and micro-resins. Do not incinerate.',
    imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&q=80',
  },
  {
    id: 'Cable',
    nameEn: 'Copper Cable',
    nameHi: 'तांबे का तार (Copper Cable)',
    nameMr: 'तांब्याची तार (Copper Cable)',
    icon: '⚡',
    avgPricePerKg: 520,
    priceRange: { min: 500, max: 540 },
    subCategories: ['Heavy Industrial Copper Wire', 'Insulated Household Power Cords', 'Submersible Cable', 'LAN / Telecom Wire'],
    description: 'Insulated & uninsulated heavy copper wiring, power cords, telecommunication lines.',
    safetyHazard: 'Never burn plastic insulation open-air. Toxic smoke release.',
    imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&q=80',
  },
  {
    id: 'LCD',
    nameEn: 'LCD Screen Panel',
    nameHi: 'एलसीडी स्क्रीन (LCD Panel)',
    nameMr: 'एलसीडी स्क्रीन (LCD Panel)',
    icon: '🖥️',
    avgPricePerKg: 85,
    priceRange: { min: 80, max: 95 },
    subCategories: ['Laptop Display Panel', 'Desktop Monitor Panel', 'LED / LCD TV Screen', 'Mobile LCD Module'],
    description: 'Flat panel monitor displays, laptop screens, TV panels.',
    safetyHazard: 'Glass shards and CCFL mercury backlight tubes.',
    imageUrl: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400&q=80',
  },
  {
    id: 'Motor',
    nameEn: 'Electric Motor',
    nameHi: 'इलेक्ट्रिक मोटर (Motor)',
    nameMr: 'इलेक्ट्रिक मोटर (Motor)',
    icon: '⚙️',
    avgPricePerKg: 180,
    priceRange: { min: 170, max: 190 },
    subCategories: ['Washing Machine Motor', 'Ceiling Fan Copper Motor', 'AC Compressor Motor', 'Power Tool Armature'],
    description: 'Copper-wound motors from washing machines, fans, compressors, power tools.',
    safetyHazard: 'Heavy iron housing. Handle with protective boots.',
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=400&q=80',
  },
  {
    id: 'CRT',
    nameEn: 'CRT Monitor/TV Glass',
    nameHi: 'पुराना टीवी/मॉनिटर (CRT)',
    nameMr: 'जुना टीव्ही/मॉनिटर (CRT)',
    icon: '📺',
    avgPricePerKg: 35,
    priceRange: { min: 30, max: 40 },
    subCategories: ['Heavy Glass TV CRT Body', 'Computer Monitor Tube', 'Phosphor Coated Funnel Glass'],
    description: 'Cathode Ray Tube glass monitors, thick heavy glass TV bodies.',
    safetyHazard: 'High risk of implosion glass rupture & toxic lead oxide coating inside.',
    imageUrl: 'https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=400&q=80',
  },
  {
    id: 'Battery',
    nameEn: 'Battery (Li-ion/Lead)',
    nameHi: 'बैटरी (Battery Pack)',
    nameMr: 'बॅटरी (Battery Pack)',
    icon: '🔋',
    avgPricePerKg: 140,
    priceRange: { min: 130, max: 155 },
    subCategories: ['Li-ion Laptop / Phone Pouches', 'UPS Sealed Lead Acid (SLA)', 'E-Bike Battery Pack', 'EV Module Cells'],
    description: 'UPS batteries, laptop batteries, phone Li-ion pouches, e-bike battery packs.',
    safetyHazard: 'Fire & explosion risk. Do not puncture or expose to heat.',
    imageUrl: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=400&q=80',
  },
  {
    id: 'Magnet assembly',
    nameEn: 'Magnet Assembly',
    nameHi: 'चुंबक असेंबली (Magnet)',
    nameMr: 'मॅग्नेट असेंब्ली (Magnet)',
    icon: '🧲',
    avgPricePerKg: 210,
    priceRange: { min: 195, max: 230 },
    subCategories: ['Neodymium HDD Magnet', 'Heavy Speaker Ferrite Magnet', 'Actuator Motor Assembly'],
    description: 'Neodymium magnets from hard disks, heavy speaker magnets, magnetic actuators.',
    safetyHazard: 'Pinch hazard for fingers due to strong magnetic attraction.',
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&q=80',
  },
  {
    id: 'Plastic',
    nameEn: 'E-Waste Plastic (ABS/PC)',
    nameHi: 'ई-कचरा प्लास्टिक (ABS)',
    nameMr: 'ई-कचरा प्लास्टिक (ABS)',
    icon: '♻️',
    avgPricePerKg: 28,
    priceRange: { min: 25, max: 32 },
    subCategories: ['Computer Outer Casing (ABS)', 'Printer / Keyboard Shells', 'Appliance Plastic Bodies'],
    description: 'Hard outer casings of computers, keyboards, printers, appliances.',
    safetyHazard: 'Flame retardant additives. Melt only in industrial furnaces.',
    imageUrl: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=400&q=80',
  },
];

export const INITIAL_PRICE_DATASET = [
  {
    id: 'PRC-001',
    material: 'PCB',
    location: 'Hadapsar, Pune',
    date: '06-09-2026',
    unit: '₹/kg',
    prevailingPrice: 420,
    recyclerOfferRange: '₹400–450',
    trend: 'up',
    history7Days: [
      { date: '31-08', price: 380 },
      { date: '02-09', price: 395 },
      { date: '04-09', price: 410 },
      { date: '06-09', price: 420 },
    ],
  },
  {
    id: 'PRC-002',
    material: 'Cable',
    location: 'Hadapsar, Pune',
    date: '06-09-2026',
    unit: '₹/kg',
    prevailingPrice: 520,
    recyclerOfferRange: '₹500–540',
    trend: 'up',
    history7Days: [
      { date: '31-08', price: 490 },
      { date: '02-09', price: 505 },
      { date: '04-09', price: 515 },
      { date: '06-09', price: 520 },
    ],
  },
  {
    id: 'PRC-003',
    material: 'LCD',
    location: 'Taloja, Navi Mumbai',
    date: '06-09-2026',
    unit: '₹/kg',
    prevailingPrice: 85,
    recyclerOfferRange: '₹80–95',
    trend: 'stable',
    history7Days: [
      { date: '31-08', price: 82 },
      { date: '02-09', price: 84 },
      { date: '04-09', price: 85 },
      { date: '06-09', price: 85 },
    ],
  },
  {
    id: 'PRC-004',
    material: 'Motor',
    location: 'Chakan, Pune',
    date: '06-09-2026',
    unit: '₹/kg',
    prevailingPrice: 180,
    recyclerOfferRange: '₹170–190',
    trend: 'up',
    history7Days: [
      { date: '31-08', price: 165 },
      { date: '02-09', price: 172 },
      { date: '04-09', price: 178 },
      { date: '06-09', price: 180 },
    ],
  },
  {
    id: 'PRC-005',
    material: 'Battery',
    location: 'Hadapsar, Pune',
    date: '06-09-2026',
    unit: '₹/kg',
    prevailingPrice: 140,
    recyclerOfferRange: '₹130–155',
    trend: 'up',
    history7Days: [
      { date: '31-08', price: 130 },
      { date: '02-09', price: 135 },
      { date: '04-09', price: 138 },
      { date: '06-09', price: 140 },
    ],
  },
];

export const VERIFIED_RECYCLERS_DATASET = [
  {
    recycler_id: 'REC-PUNE-01',
    name: 'ABC Eco-Recycling Pvt Ltd',
    location: 'Hadapsar Industrial Estate, Pune',
    distanceKm: 4.2,
    materials_accepted: ['PCB', 'Cable', 'Battery', 'Motor', 'LCD', 'Magnet assembly', 'Plastic', 'CRT'],
    authorization_details: 'MPCB/EW-REG/2024/0981 (Valid till 2028)',
    authorization_status: 'Authorized',
    contact: '+91 98220 12345',
    offered_rate_multiplier: 1.025,
    pickup_available: true,
    service_area: 'Pune East & Central',
    reliability_score: 98,
    rating: 4.9,
  },
  {
    recycler_id: 'REC-PUNE-02',
    name: 'GreenTech Metals & E-Waste Recyclers',
    location: 'Chakan MIDC Phase 2, Pune',
    distanceKm: 14.0,
    materials_accepted: ['PCB', 'Cable', 'Motor', 'CRT', 'Battery'],
    authorization_details: 'MPCB/EW-REG/2023/1142 (Valid till 2027)',
    authorization_status: 'Authorized',
    contact: '+91 94230 67890',
    offered_rate_multiplier: 1.071,
    pickup_available: false,
    service_area: 'Pimpri-Chinchwad & Chakan',
    reliability_score: 92,
    rating: 4.6,
  },
  {
    recycler_id: 'REC-PUNE-03',
    name: 'Bharat Scrap Traders (Unverified Dealer)',
    location: 'Kasba Peth, Pune',
    distanceKm: 2.1,
    materials_accepted: ['PCB', 'Cable', 'Motor', 'Plastic'],
    authorization_details: 'No formal MPCB registration',
    authorization_status: 'Unverified',
    contact: '+91 91580 99887',
    offered_rate_multiplier: 0.833,
    pickup_available: true,
    service_area: 'Old City Pune',
    reliability_score: 55,
    rating: 3.2,
  },
  {
    recycler_id: 'REC-MUMBAI-01',
    name: 'Sahyadri E-Waste Processors',
    location: 'Taloja Industrial Area, Navi Mumbai',
    distanceKm: 118.0,
    materials_accepted: ['PCB', 'Cable', 'LCD', 'Battery', 'CRT'],
    authorization_details: 'MPCB/EW-REG/2025/0419 (Valid till 2029)',
    authorization_status: 'Authorized',
    contact: '+91 98200 44556',
    offered_rate_multiplier: 1.047,
    pickup_available: true,
    service_area: 'MMR Region & Raigad',
    reliability_score: 96,
    rating: 4.8,
  },
];

export const INITIAL_COLLECTOR = {
  collector_id: 'COL-00128',
  name: 'Ramesh Pawar (रमेश पवार)',
  phone: '+91 98765 43210',
  preferred_language: 'mr',
  operating_area: 'Hadapsar / Pune',
  lots_sold: 28,
  total_earnings: 42500,
  pending_earnings: 2100,
};

export const SAFETY_GUIDELINES = [
  {
    id: 'SAF-01',
    material: 'Cable Burning',
    titleHi: 'तार जलाना सख्त मना है (Do Not Burn Wires)',
    titleMr: 'तारा जाळणे पूर्णपणे बंदी आहे (तार न जाळा)',
    titleEn: 'Do Not Burn Wires (Toxic Fumes)',
    audioTextHi: 'तार मत जलाएं। तार जलाने से जहरीला धुआं और डाइऑक्सिन गैस निकलती है।',
    audioTextMr: 'तारा जाळू नका. तार जाळल्याने विषारी धूर आणि घातक वायू हवेत पसरतो.',
    audioTextEn: 'Do not burn wires. Open burning releases carcinogenic dioxin fumes and lead smoke.',
    warningLevel: 'CRITICAL',
    icon: '🔥',
    doList: [
      'Use manual wire stripping tools to peel PVC insulation safely.',
      'Sell intact insulated wire lots directly to MPCB authorized recyclers.',
    ],
    dontList: [
      'Never set fire to plastic cable piles in open spaces or slums.',
      'Do not inhale smoke from burning PVC wire sheath.',
    ],
  },
  {
    id: 'SAF-02',
    material: 'Acid Leaching Hazard',
    titleHi: 'तेज़ाब से धातु न निकालें (Acid Leaching Prohibited)',
    titleMr: 'ॲसिडने धातू विरघळवू नका (ॲसिड लीचिंग बंदी)',
    titleEn: 'Acid Leaching Prohibited (Chemical Risk)',
    audioTextHi: 'सर्किट बोर्ड को नाइट्रिक तेज़ाब में मत डालें। इससे फेफड़ों को भारी नुकसान होता है।',
    audioTextMr: 'सर्किट बोर्ड ॲसिडमध्ये टाकू नका. यामुळे फुफ्फुसांना गंभीर इजा होऊ शकते.',
    audioTextEn: 'Do not use nitric/cyanide acid baths to extract gold/copper from PCBs manually.',
    warningLevel: 'CRITICAL',
    icon: '🧪',
    doList: [
      'Hand over bare PCBs to authorized smelters equipped with acid scrubbers.',
      'Wear nitrile protective gloves when handling chemically treated boards.',
    ],
    dontList: [
      'Do not pour toxic acid effluent into municipal drains or soil.',
      'Never boil acid in open household pots without fume extraction hoods.',
    ],
  },
  {
    id: 'SAF-03',
    material: 'Hazardous Component Disassembly',
    titleHi: 'खतरनाक पार्ट्स जबरदस्ती न खोलें (Safe Disassembly)',
    titleMr: 'धोकादायक भाग उघडू नका (सुरक्षित हाताळणी)',
    titleEn: 'No Hazardous Manual Component Crushing',
    audioTextHi: 'कैपेसिटर, मरकरी लैंप और सीलबंद बैटरियों को हथौड़े से मत तोड़ें।',
    audioTextMr: 'कॅपॅसिटर, मर्क्युरी लॅम्प किंवा सील केलेल्या बॅटऱ्या हातोड्याने फोडू नका.',
    audioTextEn: 'Do not smash high-voltage capacitors, mercury backlights, or sealed relays with hammers.',
    warningLevel: 'WARNING',
    icon: '🔨',
    doList: [
      'Unscrew outer casing intact using insulated screwdrivers.',
      'Store unsorted IC components in cushioned cardboard boxes.',
    ],
    dontList: [
      'Do not break toxic mercury CCFL tubes inside displays.',
      'Do not expose skin to leaked liquid electrolyte from capacitors.',
    ],
  },
  {
    id: 'SAF-04',
    material: 'Battery Safety',
    titleHi: 'बैटरी पंक्चर न करें (Battery Explosion Hazard)',
    titleMr: 'बॅटरी पंक्चर करू नका (बॅटरी धोका)',
    titleEn: 'Battery Fire & Explosion Safety',
    audioTextHi: 'लिथियम बैटरी को कभी मत फोड़ें या आग में डालें। इससे बड़ा विस्फोट हो सकता है।',
    audioTextMr: 'लिथियम बॅटरी फोडू नका किंवा आगीत टाकू नका. मोठा स्फोट होऊ शकतो.',
    audioTextEn: 'Do not puncture lithium pouches or short battery terminals with metal tools.',
    warningLevel: 'CRITICAL',
    icon: '🔋',
    doList: [
      'Keep damaged or swollen lithium batteries in dry sand buckets.',
      'Tape exposed battery terminals with insulation electrical tape.',
    ],
    dontList: [
      'Never dump lithium batteries in open household trash or heat sources.',
      'Do not crush swollen cell phone batteries with pliers.',
    ],
  },
  {
    id: 'SAF-05',
    material: 'CRT Glass Handling',
    titleHi: 'CRT टीवी शीशा न तोड़ें (Vacuum Glass Explosive Shards)',
    titleMr: 'CRT टीव्ही काच फोडू नका (काच धोकादायक)',
    titleEn: 'CRT Vacuum Tube Glass Protection',
    audioTextHi: 'पुराने टीवी की कांच की नली खुद मत तोड़ें। इसमें जहरीला लेड ऑक्साइड होता है।',
    audioTextMr: 'जुन्या टीव्हीची काच स्वतः फोडू नका. यात विषारी लेड ऑक्सॉइड असते.',
    audioTextEn: 'Do not smash CRT vacuum picture tubes manually. High implosion glass hazard.',
    warningLevel: 'WARNING',
    icon: '📺',
    doList: [
      'Transport CRT TV intact inside cushioned wooden crates.',
      'Wear thick leather safety gloves during handling.',
    ],
    dontList: [
      'Do not break the rear electron gun neck of the glass tube.',
      'Do not leave broken leaded glass lying open in soil.',
    ],
  },
];

export const INITIAL_DEMO_LOTS = [
  {
    lot_id: 'LOT-2026-PN-000182',
    collector_id: 'COL-00128',
    material: 'PCB',
    sub_category: 'Green Motherboard',
    material_description: '35 kg Green Motherboard & Server RAM PCBs',
    photo_url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&q=80',
    weight_kg: 35,
    condition: 'Mixed',
    estimated_value_min: 13500,
    estimated_value_max: 15000,
    quoted_price: 14700,
    final_price: 15050,
    collection_location: 'Hadapsar, Pune (18.5089° N, 73.9259° E)',
    collection_timestamp: '2026-09-05T14:30:00.000Z',
    recycler_id: 'REC-PUNE-01',
    recycler_name: 'ABC Eco-Recycling Pvt Ltd',
    handover_location: 'Hadapsar Industrial Estate, Pune',
    handover_timestamp: '2026-09-05T17:10:00.000Z',
    handover_ref: 'HND-2026-009411',
    payment_method: 'CASH',
    payment_status: 'COMPLETED',
    transaction_status: 'RECYCLED',
    sync_status: 'SYNCED',
    verified_weight_kg: 35,
  },
  {
    lot_id: 'LOT-2026-PN-000179',
    collector_id: 'COL-00128',
    material: 'Cable',
    sub_category: 'Heavy Industrial Copper Wire',
    material_description: 'Heavy gauge copper wiring from dismantled generator',
    photo_url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&q=80',
    weight_kg: 20,
    condition: 'Clean',
    estimated_value_min: 10000,
    estimated_value_max: 10800,
    quoted_price: 10400,
    final_price: 10400,
    collection_location: 'Hadapsar, Pune',
    collection_timestamp: '2026-09-02T10:30:00.000Z',
    recycler_id: 'REC-PUNE-01',
    recycler_name: 'ABC Eco-Recycling Pvt Ltd',
    handover_location: 'Hadapsar, Pune',
    handover_timestamp: '2026-09-02T14:15:00.000Z',
    handover_ref: 'HND-2026-008102',
    payment_method: 'UPI',
    payment_status: 'COMPLETED',
    transaction_status: 'RECYCLED',
    sync_status: 'SYNCED',
    verified_weight_kg: 20,
  },
];
