import { MaterialInfo, PriceRecord, Recycler, CollectorProfile, SafetyGuideline, Lot } from '../types';

export const INITIAL_MATERIALS: MaterialInfo[] = [
  {
    id: 'PCB',
    nameEn: 'PCB (Circuit Board)',
    nameHi: 'सर्किट बोर्ड (PCB)',
    nameMr: 'सर्किट बोर्ड (PCB)',
    icon: '🔌',
    avgPricePerKg: 420,
    priceRange: { min: 400, max: 450 },
    description: 'Printed Circuit Boards from Green Motherboards, RAM, GPUs, and IC boards.',
    safetyHazard: 'Contains solder lead and micro-resins. Do not incinerate.',
    imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&q=80',
  },
  {
    id: 'Cable',
    nameEn: 'Copper Cable',
    nameHi: 'तांबे का तार (Copper Cable)',
    nameMr: 'तांब्याची तार (Copper Cable)',
    icon: '⚡',
    avgPricePerKg: 520,
    priceRange: { min: 500, max: 540 },
    description: 'Insulated & uninsulated heavy copper wiring, power cords, telecommunication lines.',
    safetyHazard: 'Never burn plastic insulation open-air. Toxic smoke release.',
    imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&q=80',
  },
  {
    id: 'LCD',
    nameEn: 'LCD Screen',
    nameHi: 'एलसीडी स्क्रीन (LCD)',
    nameMr: 'एलसीडी स्क्रीन (LCD)',
    icon: '🖥️',
    avgPricePerKg: 85,
    priceRange: { min: 80, max: 95 },
    description: 'Flat panel monitor displays, laptop screens, TV panels.',
    safetyHazard: 'Glass shards and CCFL mercury backlight tubes.',
    imageUrl: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400&q=80',
  },
  {
    id: 'Motor',
    nameEn: 'Electric Motor',
    nameHi: 'इलेक्ट्रिक मोटर (Motor)',
    nameMr: 'इलेक्ट्रिक मोटर (Motor)',
    icon: '⚙️',
    avgPricePerKg: 180,
    priceRange: { min: 170, max: 190 },
    description: 'Copper-wound motors from washing machines, fans, compressors, power tools.',
    safetyHazard: 'Heavy iron housing. Handle with protective boots.',
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=400&q=80',
  },
  {
    id: 'CRT',
    nameEn: 'CRT Monitor/TV',
    nameHi: 'पुराना टीवी/मॉनिटर (CRT)',
    nameMr: 'जुना टीव्ही/मॉनिटर (CRT)',
    icon: '📺',
    avgPricePerKg: 35,
    priceRange: { min: 30, max: 40 },
    description: 'Cathode Ray Tube glass monitors, thick heavy glass TV bodies.',
    safetyHazard: 'High risk of implosion glass rupture & toxic lead oxide coating inside.',
    imageUrl: 'https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=400&q=80',
  },
  {
    id: 'Battery',
    nameEn: 'Battery (Li-ion/Lead)',
    nameHi: 'बैटरी (Battery)',
    nameMr: 'बॅटरी (Battery)',
    icon: '🔋',
    avgPricePerKg: 140,
    priceRange: { min: 130, max: 155 },
    description: 'UPS batteries, laptop batteries, phone Li-ion pouches, e-bike battery packs.',
    safetyHazard: 'Fire & explosion risk. Do not puncture or expose to heat.',
    imageUrl: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=400&q=80',
  },
  {
    id: 'Magnet assembly',
    nameEn: 'Magnet Assembly',
    nameHi: 'चुंबक असेंबली (Magnet)',
    nameMr: 'मॅग्नेट असेंब्ली (Magnet)',
    icon: '🧲',
    avgPricePerKg: 210,
    priceRange: { min: 195, max: 230 },
    description: 'Neodymium magnets from hard disks, heavy speaker magnets, magnetic actuators.',
    safetyHazard: 'Pinch hazard for fingers due to strong magnetic attraction.',
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&q=80',
  },
  {
    id: 'Plastic',
    nameEn: 'E-Waste Plastic (ABS/PC)',
    nameHi: 'ई-कचरा प्लास्टिक (Plastic)',
    nameMr: 'ई-कचरा प्लास्टिक (Plastic)',
    icon: '♻️',
    avgPricePerKg: 28,
    priceRange: { min: 25, max: 32 },
    description: 'Hard outer casings of computers, keyboards, printers, appliances.',
    safetyHazard: 'Flame retardant additives. Melt only in industrial furnaces.',
    imageUrl: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=400&q=80',
  },
];

export const INITIAL_PRICE_DATASET: PriceRecord[] = [
  {
    id: 'PRC-001',
    material: 'PCB',
    location: 'Pune',
    date: '05-09-2026',
    unit: '₹/kg',
    prevailingPrice: 420,
    recyclerOfferRange: '₹400–450',
    trend: 'up',
    history7Days: [
      { date: '30-08', price: 380 },
      { date: '01-09', price: 395 },
      { date: '03-09', price: 410 },
      { date: '05-09', price: 420 },
    ],
  },
  {
    id: 'PRC-002',
    material: 'Cable',
    location: 'Pune',
    date: '05-09-2026',
    unit: '₹/kg',
    prevailingPrice: 520,
    recyclerOfferRange: '₹500–540',
    trend: 'up',
    history7Days: [
      { date: '30-08', price: 490 },
      { date: '01-09', price: 505 },
      { date: '03-09', price: 515 },
      { date: '05-09', price: 520 },
    ],
  },
  {
    id: 'PRC-003',
    material: 'LCD',
    location: 'Mumbai',
    date: '05-09-2026',
    unit: '₹/kg',
    prevailingPrice: 85,
    recyclerOfferRange: '₹80–95',
    trend: 'stable',
    history7Days: [
      { date: '30-08', price: 82 },
      { date: '01-09', price: 84 },
      { date: '03-09', price: 85 },
      { date: '05-09', price: 85 },
    ],
  },
  {
    id: 'PRC-004',
    material: 'Motor',
    location: 'Pune',
    date: '05-09-2026',
    unit: '₹/kg',
    prevailingPrice: 180,
    recyclerOfferRange: '₹170–190',
    trend: 'up',
    history7Days: [
      { date: '30-08', price: 165 },
      { date: '01-09', price: 172 },
      { date: '03-09', price: 178 },
      { date: '05-09', price: 180 },
    ],
  },
];

export const VERIFIED_RECYCLERS_DATASET: Recycler[] = [
  {
    recycler_id: 'REC-PUNE-01',
    name: 'ABC Eco-Recycling Pvt Ltd',
    location: 'Hadapsar Industrial Estate, Pune',
    distanceKm: 4.2,
    materials_accepted: ['PCB', 'Cable', 'Battery', 'Motor', 'LCD', 'Magnet assembly', 'Plastic'],
    authorization_details: 'MPCB/EW-REG/2024/0981 (Valid till 2028)',
    authorization_status: 'Authorized',
    contact: '+91 98220 12345',
    offered_rate_multiplier: 1.025, // ₹430/kg for PCB
    pickup_available: true,
    service_area: 'Pune East & Central',
    reliability_score: 98,
    rating: 4.9,
  },
  {
    recycler_id: 'REC-PUNE-02',
    name: 'GreenTech Metals & E-Waste Recyclers',
    location: 'Chakan MIDC Phase 2, Pune',
    distanceKm: 14.0,
    materials_accepted: ['PCB', 'Cable', 'Motor', 'CRT', 'Battery'],
    authorization_details: 'MPCB/EW-REG/2023/1142 (Valid till 2027)',
    authorization_status: 'Authorized',
    contact: '+91 94230 67890',
    offered_rate_multiplier: 1.071, // ₹450/kg for PCB
    pickup_available: false, // No pickup!
    service_area: 'Pimpri-Chinchwad & Chakan',
    reliability_score: 92,
    rating: 4.6,
  },
  {
    recycler_id: 'REC-PUNE-03',
    name: 'Bharat Scrap Traders (Unverified Scrap Dealer)',
    location: 'Kasba Peth, Pune',
    distanceKm: 2.1,
    materials_accepted: ['PCB', 'Cable', 'Motor', 'Plastic'],
    authorization_details: 'No formal MPCB registration',
    authorization_status: 'Unverified',
    contact: '+91 91580 99887',
    offered_rate_multiplier: 0.833, // ₹350/kg (Under-priced)
    pickup_available: true,
    service_area: 'Old City Pune',
    reliability_score: 55,
    rating: 3.2,
  },
  {
    recycler_id: 'REC-MUMBAI-01',
    name: 'Sahyadri E-Waste Processors',
    location: 'Taloja Industrial Area, Navi Mumbai',
    distanceKm: 118.0,
    materials_accepted: ['PCB', 'Cable', 'LCD', 'Battery', 'CRT'],
    authorization_details: 'MPCB/EW-REG/2025/0419 (Valid till 2029)',
    authorization_status: 'Authorized',
    contact: '+91 98200 44556',
    offered_rate_multiplier: 1.047,
    pickup_available: true,
    service_area: 'MMR Region & Raigad',
    reliability_score: 96,
    rating: 4.8,
  },
];

export const INITIAL_COLLECTOR: CollectorProfile = {
  collector_id: 'COL-00128',
  name: 'Ramesh Pawar (रमेश पवार)',
  phone: '+91 98765 43210',
  preferred_language: 'mr',
  operating_area: 'Hadapsar / Pune',
  lots_sold: 28,
  total_earnings: 42500,
  pending_earnings: 2100,
};

export const SAFETY_GUIDELINES: SafetyGuideline[] = [
  {
    id: 'SAF-01',
    material: 'Cable',
    titleHi: 'तार जलाना सख्त मना है (Do Not Burn Wires)',
    titleMr: 'तारा जाळणे पूर्णपणे बंदी आहे (तार न जाळा)',
    titleEn: 'Do Not Burn Wires',
    audioTextHi: 'तार मत जलाएं। तार जलाने से जहरीला धुआं और हानिकारक गैस निकलती है।',
    audioTextMr: 'तारा जाळू नका. तार जाळल्याने विषारी धूर आणि घातक वायू हवेत पसरतो.',
    audioTextEn: 'Do not burn wires. Burning releases harmful toxic lead smoke.',
    warningLevel: 'CRITICAL',
    icon: '🔥',
    doList: [
      'Use manual wire stripper to peel plastic insulation.',
      'Sell intact cables directly to authorized recyclers for high copper recovery value.',
    ],
    dontList: [
      'Never burn cables in open ground or residential areas.',
      'Do not inhale smoke from heated plastic.',
    ],
  },
  {
    id: 'SAF-02',
    material: 'Battery',
    titleHi: 'बैटरी पंक्चर या गरम न करें (Battery Danger)',
    titleMr: 'बॅटरी पंक्चर करू नका (बॅटरी धोकेदायक)',
    titleEn: 'Handle Batteries Carefully',
    audioTextHi: 'बैटरी को कभी मत फोड़ें और न ही आग में डालें। इससे विस्फोट हो सकता है।',
    audioTextMr: 'बॅटरी फोडू नका किंवा आगीत टाकू नका. यामुळे मोठा स्फोट होऊ शकतो.',
    audioTextEn: 'Do not puncture batteries or throw into fire. Extreme explosion hazard.',
    warningLevel: 'CRITICAL',
    icon: '🔋',
    doList: [
      'Keep damaged or swollen lithium batteries inside dry sand bucket.',
      'Tape exposed battery terminals with electrical insulation tape.',
    ],
    dontList: [
      'Never throw batteries into open trash or fire.',
      'Do not hit batteries with hammer to break case.',
    ],
  },
  {
    id: 'SAF-03',
    material: 'CRT',
    titleHi: 'CRT शीशा मत तोड़ें (Dangerous Glass)',
    titleMr: 'CRT काच फोडू नका (काच धोकादायक)',
    titleEn: 'CRT Glass Explosion Hazard',
    audioTextHi: 'पुराने टीवी का शीशा खुद न तोड़ें। इसमें लेड और खतरनाक गैस होती है।',
    audioTextMr: 'जुन्या टीव्हीची काच स्वतः फोडू नका. यात विषारी शिसे (Lead) असते.',
    audioTextEn: 'Do not break CRT vacuum glass manually. High risk of glass implosion and lead toxic exposure.',
    warningLevel: 'WARNING',
    icon: '📺',
    doList: [
      'Transport CRT TV intact inside cushioned crate.',
      'Wear thick protective leather gloves when carrying.',
    ],
    dontList: [
      'Do not break the rear neck of the vacuum tube.',
      'Do not leave broken phosphor glass lying in soil.',
    ],
  },
];

export const INITIAL_DEMO_LOTS: Lot[] = [
  {
    lot_id: 'LOT-2026-PN-000179',
    collector_id: 'COL-00128',
    material: 'Cable',
    material_description: 'Heavy gauge copper wiring from dismantled building generator',
    photo_url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&q=80',
    weight_kg: 20,
    condition: 'Clean',
    estimated_value_min: 10000,
    estimated_value_max: 10800,
    quoted_price: 10400,
    final_price: 10400,
    collection_location: 'Hadapsar, Pune',
    collection_timestamp: '2026-09-02T10:30:00.000Z',
    recycler_id: 'REC-PUNE-01',
    recycler_name: 'ABC Eco-Recycling Pvt Ltd',
    handover_location: 'Hadapsar, Pune',
    handover_timestamp: '2026-09-02T14:15:00.000Z',
    payment_method: 'UPI',
    payment_status: 'COMPLETED',
    transaction_status: 'RECYCLED',
    sync_status: 'SYNCED',
    verified_weight_kg: 20,
  },
  {
    lot_id: 'LOT-2026-PN-000180',
    collector_id: 'COL-00128',
    material: 'Motor',
    material_description: '3 washing machine motors with copper winding',
    photo_url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=400&q=80',
    weight_kg: 15,
    condition: 'Mixed',
    estimated_value_min: 2550,
    estimated_value_max: 2850,
    quoted_price: 2700,
    final_price: 2700,
    collection_location: 'Magarpatta, Pune',
    collection_timestamp: '2026-09-03T11:00:00.000Z',
    recycler_id: 'REC-PUNE-01',
    recycler_name: 'ABC Eco-Recycling Pvt Ltd',
    handover_location: 'Hadapsar Industrial Estate, Pune',
    handover_timestamp: '2026-09-03T16:00:00.000Z',
    payment_method: 'CASH',
    payment_status: 'COMPLETED',
    transaction_status: 'RECYCLED',
    sync_status: 'SYNCED',
    verified_weight_kg: 15,
  },
];
